#define INTEGRITY_BUGGY 200
#define INTEGRITY_CAR 300
#define INTEGRITY_TRUCK 400
#define INTEGRITY_ARMORED_CAR 500
#define INTEGRITY_VERTIBIRD 300

#define SPEED_BUGGY 0.8
#define SPEED_CAR 1.2
#define SPEED_TRUCK 2
#define SPEED_SUPERCAR 0.8
#define SPEED_VERTIBIRD_ATTACK 1
#define SPEED_VERTIBIRD_TRANSPORT 0.8
#define SPEED_BALLOON 2
